version: '3'

services:
  server:
    build: .
    image: server
    ports:
      - '${PROFILE_SERVICE_PORT}:${PROFILE_SERVICE_PORT}'
    command: npm run start
    volumes:
      - ./:/app
    depends_on:
      - db
  db:
    image: postgres:12.4
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - 'db-data:/var/lib/postgresql/data'
    ports:
      - '${POSTGRES_PORT}:5432'
  pgadmin:
    image: dpage/pgadmin4:4.25
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
    ports:
      - '${PGADMIN_PORT}:80'
    volumes:
      - 'pgadmin-data:/var/lib/pgadmin'
    depends_on:
      - db

volumes:
  db-data:
  pgadmin-data:
